kind: PersistentVolume
apiVersion: v1
metadata:
  name: mylocal02
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/ephemere"
