kind: Pod
apiVersion: v1
metadata:
  name: mypod02b
  labels:
    name: frontendhttp02b
spec:
  containers:
    - name: myfrontend02
      image: golang:1.4
      volumeMounts:
      - mountPath: "/tmp/writehere"
        name: myvolume02
  volumes:
    - name: myvolume02
      persistentVolumeClaim:
       claimName: myclaim02
